create table public.batch (
  batch_entry_date date not null,
  batch_number text not null,
  origin text null,
  purchase_status public.status_enum null,
  boiling_status public.status_enum null,
  nw_drying_status public.status_enum null,
  nw_humidification_status public.status_enum null,
  peeling_before_drying_status public.status_enum null,
  peeling_after_drying_status public.status_enum null,
  production_status public.status_enum null,
  cashew_kernel_sales_status public.status_enum null,
  rcn_sales_status public.status_enum null,
  purchase_updated_at timestamp without time zone null,
  purchase_updated_by uuid null,
  boiling_updated_at timestamp without time zone null,
  boiling_updated_by uuid null,
  nw_drying_updated_at timestamp without time zone null,
  nw_drying_updated_by uuid null,
  nw_humidification_updated_at timestamp without time zone null,
  nw_humidification_updated_by uuid null,
  peeling_before_drying_updated_at timestamp without time zone null,
  peeling_before_drying_updated_by uuid null,
  peeling_after_drying_updated_at timestamp without time zone null,
  peeling_after_drying_updated_by uuid null,
  production_updated_at timestamp without time zone null,
  production_updated_by uuid null,
  cashew_kernel_sales_updated_at timestamp without time zone null,
  cashew_kernel_sales_updated_by uuid null,
  rcn_sales_updated_at timestamp without time zone null,
  rcn_sales_updated_by uuid null,
  is_deleted boolean null default false,
  created_by uuid null,
  created_at timestamp without time zone null default now(),
  updated_by uuid null,
  updated_at timestamp without time zone null,
  constraint batch_pkey primary key (batch_number),
  constraint batch_cashew_kernel_sales_updated_by_fkey foreign KEY (cashew_kernel_sales_updated_by) references users (id),
  constraint batch_created_by_fkey foreign KEY (created_by) references users (id),
  constraint batch_nw_drying_updated_by_fkey foreign KEY (nw_drying_updated_by) references users (id),
  constraint batch_nw_humidification_updated_by_fkey foreign KEY (nw_humidification_updated_by) references users (id),
  constraint batch_peeling_after_drying_updated_by_fkey foreign KEY (peeling_after_drying_updated_by) references users (id),
  constraint batch_peeling_before_drying_updated_by_fkey foreign KEY (peeling_before_drying_updated_by) references users (id),
  constraint batch_production_updated_by_fkey foreign KEY (production_updated_by) references users (id),
  constraint batch_purchase_updated_by_fkey foreign KEY (purchase_updated_by) references users (id),
  constraint batch_rcn_sales_updated_by_fkey foreign KEY (rcn_sales_updated_by) references users (id),
  constraint batch_boiling_updated_by_fkey foreign KEY (boiling_updated_by) references users (id),
  constraint batch_updated_by_fkey foreign KEY (updated_by) references users (id)
) TABLESPACE pg_default;